/*
 * MIT License
 *
 * Copyright (c) 2024 CookieGMVN and contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

export interface BalanceData {
    number: string,
    name: string,
    currency: string,
    balance: string,
}

export interface BalanceList {
    balances?: BalanceData[],
    internationalBalances?: BalanceData[],
    currencyEquivalent: string,
    totalBalance: string,
}

export interface TransactionInfo {
    postDate: string,
    transactionDate: string,
    accountNumber: string,
    creditAmount: string,
    debitAmount: string,
    transactionCurrency: string,
    transactionDesc: string,
    balanceAvailable: string,
    refNo: string,
    toAccountName?: string,
    toBank?: string,
    toAccountNumber?: string,
    type?: string,
}

// Generated by Claude AI. Bro this is crazy!
export interface LoginResponseData {
    refNo: string;
    result: {
      message: string;
      ok: boolean;
      responseCode: string;
    };
    sessionId: string;
    cust: {
      id: string;
      addr1: string;
      addr2: string;
      addr3: string | null;
      chrgAcctCd: string;
      cityCd: string | null;
      correspondentEmail: string;
      createdBy: string;
      creditFrameworkBranch: string | null;
      creditFrameworkContract: string | null;
      custSectorCd: string;
      email1: string;
      email2: string | null;
      entrustId: string;
      hndlingOfficerCd: string;
      hostCifId: string;
      idTypDt: number;
      idTypDtValue: null;
      idTypNo: string;
      idTypPlace: string;
      idTypType: string;
      idExpiryDate: number;
      isDelete: string;
      isInactive: string;
      isLoan: string;
      mobilePhoneNo1: string;
      mobilePhoneNo2: string | null;
      dob: string;
      dobObj: number;
      nm: string;
      orgUnitCd: string;
      phoneNo: string;
      secHndlingOfficerCd: string;
      spiUsrCd: string;
      srvcPcCd: string;
      stateCd: string | null;
      userId: string;
      state: number;
      gender: string;
      password: string;
      imUserStatus: string;
      auth_type: string | null;
      device_no: string | null;
      chargeCd: string | null;
      menuCd: string | null;
      limitCd: string | null;
      acct_list: {
        [accountNumber: string]: {
          acctNo: string;
          acctAlias: string;
          acctNm: string;
          acctTypCd: string;
          ccyCd: string;
          custId: string;
          hostCustId: string;
          inactiveSts: string;
          orgUnitCd: string;
          isCrdt: string;
          isDebit: string;
          isInq: string;
          currentBalance: string | null;
          isSync: string | null;
          category: string;
          productType: string;
        };
      };
      cardList: {
        [cardNumber: string]: {
          id: string | null;
          acctNm: string;
          acctNo: string;
          alwOverLmtPerDay: string | null;
          alwOverNoTrxPerDay: string | null;
          billingDt: string | null;
          cardCatCd: string | null;
          cardFlag: string | null;
          cardLvl: string;
          cardNm: string;
          cardNo: string;
          cardPrdCd: string;
          cardTyp: string;
          ccyCd: string;
          creditLmt: number | null;
          hostCustId: string;
          isAccsEbanking: string | null;
          orgUnitCd: string | null;
          pmryCardNm: string;
          pmryCardNo: string;
          prdTypCd: string | null;
          splmtryFlag: string | null;
          sts: string;
          stsCard: string | null;
          stsInetUsage: string;
          validThrough: string;
          cardCtkd: string | null;
          branchCode: string | null;
          cardDisplay: string | null;
          amountAvailable: string | null;
          interestRate: string | null;
          type: string | null;
          activeDate: string | null;
          groupDebit: string | null;
          outstandingBalance: string | null;
          totalWithDrawInMonth: string | null;
          maxWithDraw: string | null;
          err: string | null;
          messageErr: string | null;
          embossedName: string | null;
          minPaymentAmount: string | null;
          cardStatusDetail: string | null;
          contractStatusName: string | null;
          regNumber: string | null;
          isConfirm: string;
          isSourceDebit: string | null;
          cardNumber: string | null;
          packIncActive: string | null;
          plasticStatus: string | null;
          productStatus: string | null;
          contractStatusCode: string | null;
          approvalStatus: string | null;
          cardCode: string | null;
          cardClassDetail: string | null;
          isExtendValid: string | null;
          paidAmount: string | null;
          currentMinPayment: string | null;
          currentPayment: string | null;
          debtMoment: string | null;
          totalDebitAmount: string | null;
          printingStatus: string | null;
          cardProgramCd: string | null;
          debitMethod: string | null;
          cardOpenDate: string | null;
          printAddress: string | null;
          printDt: string | null;
          channel: string | null;
          htnt: string | null;
          addtionalCard: string | null;
          rbsNumber: string | null;
          typeTemplate: string | null;
          tokenStatus: string | null;
          tokenCode: string | null;
          serialId: string | null;
        };
      };
      saving_acct_list: Record<string, unknown>;
      photoStr: string | null;
      maxInactiveInterval: string;
      menuList: Array<{
        code: string;
        name: string;
        parentCode: string | null;
        priority: string;
        menuType: string;
        icon: string | null;
        url: string;
      }>;
      lastLogin: string;
      ctryCd: string;
      refNumber: string | null;
      createdDt: number;
      isSoftToken: string;
      softTokenList: Array<{
        deviceNo: string;
        custId: string;
        deviceType: string;
        isDefault: string;
        clazz: string;
        isReset: string | null;
        isMtAssigned: string | null;
        deviceId: string;
        token: string;
        status: string;
        retry: number;
        mobileDeviceId: string;
        phoneId: string;
        assignedDt: string | null;
        registeredDt: number;
        userId: string | null;
        activedOtp: string | null;
        smsCount: string | null;
        hashUserId: string | null;
        bioId: string | null;
        bioLevel: string | null;
        dotpPin: string | null;
        pinUpdateDate: string;
        hashDeviceNo: string | null;
        hashCifId: string;
        finalHashbankUID: string | null;
      }>;
      deviceId: string;
      authDevice: string | null;
      isMBCust: string;
      promotionUserList: string | null;
      isAcceptDigitalOTP: string;
      sectorDetail: {
        "Priority Sector": string;
        "Private sector": string;
      };
      isOnlineSector: string;
      smsCount: string | null;
      corpBook: string;
      isNeedUpdateLimit: string | null;
      biomatricAuthDeviceList: Array<{
        deviceNo: string;
        custId: string;
        deviceType: string;
        isDefault: string;
        clazz: string;
        isReset: string | null;
        isMtAssigned: string | null;
        deviceId: string;
        token: string | null;
        status: string;
        retry: number;
        mobileDeviceId: string | null;
        phoneId: string | null;
        assignedDt: string | null;
        registeredDt: number;
        userId: string | null;
        activedOtp: string | null;
        smsCount: string | null;
        hashUserId: string;
        bioId: string;
        bioLevel: string;
        dotpPin: string | null;
        pinUpdateDate: string;
        hashDeviceNo: string | null;
        hashCifId: string;
        finalHashbankUID: string;
      }>;
      inactiveReason: string | null;
      defaultAccount: string | null;
      passportExpDate: string | null;
      requestId: string | null;
      rcfromState: string;
      kyc: string | null;
    };
    menuManager: Array<{
      code: string;
      version: string;
      isActive: string;
      maintenanceStartTime: string | null;
      maintenanceEndTime: string | null;
    }>;
    interfaceType: {
      code: string;
      name: string;
    };
    maskingPhone: string | null;
    listPhoneId: string | null;
    existPin: string | null;
    flagLoginSms: string | null;
    webSecurityToken: string | null;
  }